### ISSUE TITLE
Cannot read property 'parent' of undefined

### ISSUE THREAD

**Issue by huan086** [ben-eb/postcss-convert-values#27]
Since commit 9f62a0f26976b4b3c965e4a75539e2062e92a07f, I'm getting the error Cannot read property 'parent' of undefined. Could you add a check in shouldStripPercent?

  
```
function shouldStripPercent ({value, prop, parent}) {
    return ~value.indexOf('%') &&
        prop === 'max-height' ||
        prop === 'height' ||
+        parent &&
        parent.parent &&
        parent.parent.name === 'keyframes' &&
        prop === 'stroke-dasharray' ||
        prop === 'stroke-dashoffset' ||
        prop === 'stroke-width';
}
```

No idea what's the root cause for parent to be undefined. My browserify plugin list is as follow

```

        const browserifyPlugins = [
            [cssModulesify, {
                output: cssOutputPath, // we need to specify output when using multiple browserify instance
                use: [fixFilePath({ to: cssOutputPath }), cssModuleCore.values, localByDefault, cssModuleCore.extractImports, cssModuleScope],
                postcssAfter: [
                    postcssUrl,
                    autoprefixer({ browsers: ['> 1%', 'IE 9', 'IE 10', 'IE 11'], remove: false }),
                    cssnano({
                        autoprefixer: { disable: true },
                        postcssDiscardDuplicates: { disable: true },
                        postcssConvertValues: { length: false },
                        postcssDiscardUnused: { disable: true },
                        postcssReduceIdents: { counterStyle: false, keyframes: false },
                        postcssZindex: { disable: true }
                    })
                ]
            }],
            collapseRequire,
            [factorBundle, factorOptions]
        ];

```

**Comment by ben-eb** [comment]
Would you be able to provide a minimal reproduction example, please? All PostCSS nodes should have a `parent` property, so I don't know where this is coming from.

**Comment by huan086** [comment]
I've updated `postcss-modules-extract-imports`, `postcss-modules-scope` and `postcss-modules-values` and no longer getting corrupted AST.

**Comment by ben-eb** [comment]
Glad you solved this. 👍

**Comment by jhpratt** [comment]
@ben-eb Same issue. I'm using an empty CSS file (though it doesn't matter if there's anything in it), and the only thing being added (`* { box-sizing: border-box; }`) is enough to break this. The plugin is written by Jon Neal, so I'd say it's a safe bet that it doesn't break the AST.

Here's the stack I'm using (minimal example)

```javascript
postcss: [
    require('postcss-time-machine'),
    require('cssnano')({ autoprefixer: false }),
]
```

It throws this error:
```
Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.14, but postcss-convert-values uses 5.2.18. Perhaps this is the source of the error below.

events.js:160
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'parent' of undefined
    at shouldStripPercent (node_modules/postcss-convert-values/dist/index.js:57:89)
    at node_modules/postcss-convert-values/dist/index.js:70:39
    at walk (node_modules/postcss-value-parser/lib/walk.js:7:22)
    at ValueParser.walk (node_modules/postcss-value-parser/lib/index.js:18:5)
    at postcss-convert-values/dist/index.js:68:68
    at node_modules/postcss/lib/container.js:188:28
    at node_modules/postcss/lib/container.js:144:26
    at Rule.each (node_modules/postcss/lib/container.js:110:22)
    at Rule.walk (node_modules/postcss/lib/container.js:143:21)
    at node_modules/postcss/lib/container.js:146:32
```
